---
abstract: 'API for Mixpanel online analytics'
author:
  - 'Tom Eliaz'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300031, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Mixpanel
requires:
  Digest::MD5: 0
  JSON: 0
  LWP::UserAgent: 0
  MIME::Base64: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  homepage: https://github.com/tomeliaz/WWW-Mixpanel
  repository: https://github.com/tomeliaz/WWW-Mixpanel.git
version: 0.06
