---
abstract: 'API for Mixpanel online analytics'
author:
  - 'Tom Eliaz'
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110580'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Mixpanel
requires:
  Carp: 0
  Digest::MD5: 0
  JSON: 0
  LWP::UserAgent: 0
  MIME::Base64: 0
  perl: 5.006
resources:
  homepage: http://github.com/tomeliaz/WWW-Mixpanel/tree
  repository: git://github.com/tomeliaz/WWW-Mixpanel.git
version: 0.02
